# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import frequencyCalculator_pb2 as frequencyCalculator__pb2


class frequencyCalculatorStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calculate = channel.unary_unary(
                '/frequencyCalculator/Calculate',
                request_serializer=frequencyCalculator__pb2.Text.SerializeToString,
                response_deserializer=frequencyCalculator__pb2.KeyPairs.FromString,
                )
        self.Combine = channel.unary_unary(
                '/frequencyCalculator/Combine',
                request_serializer=frequencyCalculator__pb2.KeyPairs.SerializeToString,
                response_deserializer=frequencyCalculator__pb2.KeyPairs.FromString,
                )


class frequencyCalculatorServicer(object):
    """The greeting service definition.
    """

    def Calculate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Combine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_frequencyCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calculate,
                    request_deserializer=frequencyCalculator__pb2.Text.FromString,
                    response_serializer=frequencyCalculator__pb2.KeyPairs.SerializeToString,
            ),
            'Combine': grpc.unary_unary_rpc_method_handler(
                    servicer.Combine,
                    request_deserializer=frequencyCalculator__pb2.KeyPairs.FromString,
                    response_serializer=frequencyCalculator__pb2.KeyPairs.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'frequencyCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class frequencyCalculator(object):
    """The greeting service definition.
    """

    @staticmethod
    def Calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/frequencyCalculator/Calculate',
            frequencyCalculator__pb2.Text.SerializeToString,
            frequencyCalculator__pb2.KeyPairs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Combine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/frequencyCalculator/Combine',
            frequencyCalculator__pb2.KeyPairs.SerializeToString,
            frequencyCalculator__pb2.KeyPairs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
